version: '3.9'

services:
  web:
    image: "shossainova1/goloco-webapp:${CPU}"
    command: gunicorn app:server -b 0.0.0.0:8080
    container_name: app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ${CERES_INFER_MODELS_PATH}:/app/ceres-infer

  worker:
    image: "shossainova1/goloco-webapp:${CPU}"
    command: celery -A app.celery_app worker --loglevel=INFO --concurrency=2
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ${CERES_INFER_MODELS_PATH}:/app/ceres-infer

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"