[build-system]
requires = [
	"numpy>=1.2", "pandas>=1.3", "tensorflow>2", "h5py>=3.7", "patsy>=0.5.2",
	"matplotlib>=3.6", "seaborn>=0.12", "scikit-learn>=1.1", "statsmodels>=0.13", "scipy>=1.9",
	"adjustText",
	"umap-learn>=0.5.3",
	"reportlab>=3.6"
]
build-backend = "setuptools.build_meta"

[project]
name = "crispr_chronos"
version = "2.0.6"
authors = [
  { name="Joshua Dempster", email="cds@broadinstitute.org" },
]
description = "A package for processing readcount data from CRISPR knockout viability experiments"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Development Status :: 5",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic:: Scientific/Engineering :: Bio-Informatics",
]

[project.urls]
"Homepage" = "https://github.com/broadinstitute/chronos"
"Bug Tracker" = "https://github.com/broadinstitute/chronos/issues"
